/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.linaro.glmark2c;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher_background=0x7f020000;
        public static final int ic_launcher_foreground=0x7f020001;
        public static final int ic_menu_archive=0x7f020002;
        public static final int ic_menu_delete=0x7f020003;
        public static final int ic_menu_info_details=0x7f020004;
        public static final int ic_menu_mark=0x7f020005;
        public static final int ic_menu_matk=0x7f020006;
        public static final int ic_menu_preferences=0x7f020007;
        public static final int ic_menu_save=0x7f020008;
    }
    public static final class id {
        public static final int about=0x7f080015;
        public static final int benchmarkListView=0x7f08000a;
        public static final int buttonLinearLayout=0x7f080006;
        public static final int copyright=0x7f080002;
        public static final int delete_benchmark_list=0x7f080013;
        public static final int description=0x7f080001;
        public static final int editorListView=0x7f080009;
        public static final int external=0x7f080010;
        public static final int license1=0x7f080004;
        public static final int license2=0x7f080005;
        public static final int listHeader=0x7f08000c;
        public static final int listName=0x7f08000f;
        public static final int load_benchmark_list=0x7f080012;
        public static final int name_version=0x7f080000;
        public static final int results=0x7f08000b;
        public static final int runButton=0x7f080007;
        public static final int saveButton=0x7f080008;
        public static final int save_benchmark_list=0x7f080011;
        public static final int settings=0x7f080014;
        public static final int summary=0x7f08000e;
        public static final int title=0x7f08000d;
        public static final int url=0x7f080003;
    }
    public static final class layout {
        public static final int activity_about=0x7f040000;
        public static final int activity_editor=0x7f040001;
        public static final int activity_main=0x7f040002;
        public static final int activity_results=0x7f040003;
        public static final int list_header=0x7f040004;
        public static final int list_item=0x7f040005;
        public static final int save_dialog=0x7f040006;
    }
    public static final class menu {
        public static final int main_options_menu=0x7f070000;
    }
    public static final class mipmap {
        public static final int ic_launcher=0x7f030000;
        public static final int ic_launcher_round=0x7f030001;
    }
    public static final class string {
        public static final int aboutMainOptionsText=0x7f06000e;
        public static final int about_copyright=0x7f060018;
        public static final int about_description=0x7f060017;
        public static final int about_license_1=0x7f06001a;
        public static final int about_license_2=0x7f06001b;
        public static final int about_name_version_format=0x7f060016;
        public static final int about_url=0x7f060019;
        public static final int app_name=0x7f060000;
        public static final int deleteMainOptionsText=0x7f06000b;
        public static final int externalSaveDialogText=0x7f06000f;
        public static final int loadMainOptionsText=0x7f06000a;
        public static final int logDebugPreferenceSummary=0x7f060013;
        public static final int logDebugPreferenceTitle=0x7f060012;
        public static final int resultsMainOptionsText=0x7f06000d;
        public static final int runButtonText=0x7f060007;
        public static final int runForeverPreferenceSummary=0x7f060011;
        public static final int runForeverPreferenceTitle=0x7f060010;
        public static final int saveButtonText=0x7f060008;
        public static final int saveMainOptionsText=0x7f060009;
        public static final int settingsMainOptionsText=0x7f06000c;
        public static final int showResultsPreferenceSummary=0x7f060015;
        public static final int showResultsPreferenceTitle=0x7f060014;
        public static final int title_activity_about=0x7f060004;
        public static final int title_activity_editor=0x7f060002;
        public static final int title_activity_glmark2=0x7f060006;
        public static final int title_activity_main=0x7f060001;
        public static final int title_activity_preferences=0x7f060003;
        public static final int title_activity_results=0x7f060005;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
    }
}
